### ISSUE TITLE
IsReadOnly allow to delete Folders

### ISSUE THREAD

**Issue by ddmactive** [gordon-matt/elFinder.NetCore#15]
Hello, I need to set permissions based on users roles. When i setup IsReadOnly =true i cant upload files but can delete folders. How can i lock all folders and files?

Thanks in advance.

**Comment by gordon-matt** [comment]
Hi there. Thanks for logging this issue. I've not had much time to look at this yet because of other work, but I did just release a new version on NuGet.. I did address part of the problem and you shouldn't be able to delete files anymore when `IsReadOnly = true`. However, I will leave this issue open for the following reasons:

1. There are more things to consider, like "Rename", "Resize", etc... I need to check and make sure those can't be done in readonly mode either.

2. The Azure Connector needs to be checked as well. @fsmirne, could you look into that for Azure?

**Comment by gordon-matt** [comment]
Thanks, @fsmirne. New NuGet package has been released. Give it a few minutes or so to be listed and indexed.

**Comment by ddmactive** [comment]
Thank you very much to both of you for your excellent work
