### ISSUE TITLE
How to view files using a custom viewer

### ISSUE THREAD

**Issue by shiyee** [gordon-matt/elFinder.NetCore#23]
Hi Sir,

You make a good file manager, thank you.

I have a question , I want to view files using a custom viewer, for example , use pdf.js to open pdf files. 

how can I do that.

thank you.

**Comment by gordon-matt** [comment]
Thank you for your nice comments, but I think you are confusing this C# connector library with the actual file manager, which is just JavaScript. The elFinder project can be found here:
https://github.com/Studio-42/elFinder

I think you will need to ask them your question instead of me. My project just lets you integrate elFinder with .NET Core projects.

Good luck.
