### ISSUE TITLE
Files Not Opening

### ISSUE THREAD

**Issue by bmin2** [gordon-matt/elFinder.NetCore#7]
Hello Sir,

I have changed my root directory to "C:\test\Files" and elfinder manages to show the files that are in the folder, but it can not preview or insert them into tinymce editor. Moreover, only those two default pictures work (Lizardmeer, Canada and Mountains) -  any other picture does not.

By work I mean that I can open the picture from elfinder and also insert it into tinymce. 
Can you help me with this issue?

**Comment by gordon-matt** [comment]
Sorry but that's not supported. Your root directory should be a sub directory of your site. If you create the functionality to change the location to be somewhere else, I'm happy for you to create a pull request and I can maybe merge that new functionality, but unfortunately I don't have the time to look into this and to be honest, I am not so sure it can even be possible, because how will your urls to the file work? For example: http://your-site.com/Files/Uploads/my-file.png (how will you get a URL if it's in C: drive root somewhere?) I think you would need to write a new FileSystemDriver that can take that kind of URL but look in a totally different place like you want.
