### ISSUE TITLE
Cannot delete file if upload by external ftp service and not by Elfinder.

### ISSUE THREAD

**Issue by biapar** [gordon-matt/elFinder.NetCore#9]
Cannot delete file if upload by external ftp service and not by Elfinder.
If you try to upload a file by ftp or copy it, you are not able to delete it by Elfinder manager.
You are able to delete if you upload file by Elfinder.

**Comment by gordon-matt** [comment]
I just tried copying a file over to the uploads folder via the file system and I was able to view it and delete it without any issue in elFinder. I have not tried this via FTP as I don't currently have access to an FTP service, but surely that shouldn't make a difference how it's copied. It makes me think there's something else going on with your environment. Did you try to delete other files that were uploaded via the file manager as well? Because I am thinking maybe you have a folder permissions problem or some other such issue.

**Comment by gordon-matt** [comment]
Closing this issue due to not being able to replicate the issue and no response from the OP.
